app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /api/

graphql:
    resource: "@GraphQLBundle/Controller/"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc